export const FETCH_SAGA = 'FETCH_SAGA';

export const SAVE_ALL_DATA = 'SAVE_ALL_DATA';
export const SAVE_ALL_COLUMNS = 'SAVE_ALL_COLUMNS';
export const SAVE_FIRST_RANGE_DATE = 'SAVE_FIRST_RANGE_DATE';

export const SET_MODAL_FLAG = 'SET_MODAL_FLAG';

export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
