export const FETCH_SAGA = 'FETCH_SAGA';

export const SAVE_ALL_DATA = 'SAVE_ALL_DATA';
export const SAVE_ALL_COLUMNS = 'SAVE_ALL_COLUMNS';
export const SAVE_FIRST_RANGE_DATE = 'SAVE_FIRST_RANGE_DATE';
export const SAVE_MAX_VALUE = 'SAVE_MAX_VALUE';

export const SET_MODAL_FLAG = 'SET_MODAL_FLAG';
export const SET_LOADER_FLAG = 'SET_LOADER_FLAG';

export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const ADD_COLUMNS_QUANTITY = 'ADD_COLUMNS_QUANTITY';
